# Generated by Django 3.2.9 on 2021-11-15 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cursos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_curso', models.IntegerField()),
                ('nome_curso', models.CharField(max_length=50)),
                ('cod_curso_5e', models.IntegerField()),
                ('cod_grade', models.IntegerField()),
                ('cod_coordenador', models.CharField(max_length=50)),
                ('modalidade', models.CharField(max_length=50)),
                ('nivel', models.CharField(max_length=50)),
            ],
        ),
    ]
