# Generated by Django 3.2.9 on 2021-11-23 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Disciplina',
            fields=[
                ('DisciplinaId', models.AutoField(primary_key=True, serialize=False)),
                ('NomeDisciplina', models.CharField(max_length=100)),
                ('CargaHoraria', models.CharField(max_length=100)),
                ('Ementa', models.CharField(max_length=100)),
                ('Habilidades', models.CharField(max_length=100)),
                ('Competencias', models.CharField(max_length=100)),
                ('CodProcedimentos', models.CharField(max_length=100)),
                ('CodSistematica', models.CharField(max_length=100)),
                ('CodCronograma', models.CharField(max_length=100)),
            ],
        ),
    ]
