# Generated by Django 3.2.8 on 2021-12-02 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disciplinaApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disciplina',
            name='Competencias',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='disciplina',
            name='Ementa',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='disciplina',
            name='Habilidades',
            field=models.CharField(max_length=1000),
        ),
    ]
