# Generated by Django 3.2.8 on 2021-12-03 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disciplinaApp', '0002_auto_20211202_2015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disciplina',
            name='CodCronograma',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='disciplina',
            name='CodProcedimentos',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='disciplina',
            name='CodSistematica',
            field=models.IntegerField(),
        ),
    ]
