# Generated by Django 3.2.8 on 2021-12-03 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disciplinaApp', '0003_auto_20211203_0128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disciplina',
            name='CodCronograma',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='disciplina',
            name='CodProcedimentos',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='disciplina',
            name='CodSistematica',
            field=models.CharField(max_length=100),
        ),
    ]
