# Generated by Django 3.2.8 on 2021-12-02 23:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('disciplinaApp', '0002_auto_20211202_2015'),
    ]

    operations = [
        migrations.CreateModel(
            name='Biblioteca',
            fields=[
                ('cod_biblioteca', models.AutoField(primary_key=True, serialize=False)),
                ('nome_biblioteca', models.CharField(max_length=100)),
                ('sigla_biblioteca', models.CharField(max_length=100)),
                ('modalidade_virtual', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Livros',
            fields=[
                ('cod_livro', models.AutoField(primary_key=True, serialize=False)),
                ('ISBN', models.CharField(max_length=100)),
                ('Titulo_livro', models.CharField(max_length=100)),
                ('autor_livro', models.CharField(max_length=100)),
                ('edicao_livro', models.CharField(max_length=100)),
                ('ano_ancamento', models.CharField(max_length=100)),
                ('cod_biblioteca', models.CharField(max_length=100)),
                ('link_livro', models.CharField(max_length=100)),
                ('status_livro', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='DisciplinaLivro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bibliografia_basica', models.CharField(max_length=100)),
                ('DisciplinaId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='DisciplinaLivro', to='disciplinaApp.disciplina')),
                ('cod_livro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='DisciplinaLivro', to='Livros.livros')),
            ],
        ),
    ]
