# Generated by Django 3.2.8 on 2021-12-03 02:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('editoraApp', '0001_initial'),
        ('Livros', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='livros',
            name='editora_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='Editora', to='editoraApp.editora'),
            preserve_default=False,
        ),
    ]
