# Generated by Django 3.2.8 on 2021-11-16 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Editora',
            fields=[
                ('EditoraId', models.AutoField(primary_key=True, serialize=False)),
                ('NomeEditora', models.CharField(max_length=100)),
                ('LocalEditora', models.CharField(max_length=100)),
            ],
        ),
    ]
