# Generated by Django 3.2.7 on 2021-11-07 19:46

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Professores',
            fields=[
                ('cod_professor', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome_professor', models.CharField(max_length=320)),
                ('codigo_acesso', models.CharField(max_length=16)),
                ('matricula', models.IntegerField()),
                ('formacao', models.CharField(max_length=1024)),
                ('titulacao', models.CharField(max_length=320)),
                ('resgistrado_desde', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
