# Generated by Django 3.2.7 on 2021-11-07 21:40

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('professores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cursos',
            fields=[
                ('cod_curso', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Disciplinas',
            fields=[
                ('cod_disciplina', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Disciplina_Professor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_disciplina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='professores.disciplinas')),
                ('cod_professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='professores.professores')),
            ],
        ),
        migrations.CreateModel(
            name='Curso_Professor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='professores.cursos')),
                ('cod_professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='professores.professores')),
            ],
        ),
    ]
